"""Initial migration

Revision ID: a875bccdc060
Revises: 
Create Date: 2026-10-06 14:58:53.596283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a875bccdc060'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('client_id_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_secret_expires_at', sa.DateTime(), nullable=False),
    sa.Column('client_name', sa.String(length=60), nullable=False),
    sa.Column('grant_type', sa.JSON(), nullable=False),
    sa.Column('client_type', sa.String(length=60), nullable=False),
    sa.Column('redirect_uris', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('auth_detail',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('jwt_token', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('auth_id', 'jwt_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_detail')
    op.drop_table('client')
    # ### end Alembic commands ###
